### ISSUE TITLE
Stopped filling in sound and translations

### ISSUE THREAD

**Issue by Hanxrion** [scottgigante/korean-support#30]
I installed the addon the other day and it worked fine.  It randomly stopped working.

I've reinstalled the addon, but that doesn't fix it.

**Comment by cereska** [comment]
@Hanxrion I'm just a fellow user of this add-on, but it works for me just fine. Do you have the add-on button active? It should be underlined like this: 
![obraz](https://user-images.githubusercontent.com/51246982/125038555-d5675500-e095-11eb-9c74-1ca837266811.png)

If you do and the issue is still happening, it might be worth to provide the author with more details so that he can try to reproduce this issue on his end, like Anki version, operating system, note type you selected, what tts you have enabled, what are your exact steps, are you getting any error messages, does it happen in the browser or add new note window etc. You can also paste the debug info copied from Anki's about window.

**Comment by Hanxrion** [comment]
> 
> 
> @Hanxrion I'm just a fellow user of this add-on, but it works for me just fine. Do you have the add-on button active? It should be underlined like this:
> ![obraz](https://user-images.githubusercontent.com/51246982/125038555-d5675500-e095-11eb-9c74-1ca837266811.png)
> 
> If you do and the issue is still happening, it might be worth providing the author with more details so that he can try to reproduce this issue on his end, like Anki version, operating system, note type you selected, what tts you have enabled, what are your exact steps, are you getting any error messages, does it happen in the browser or add new note window etc. You can also paste the debug info copied from Anki's about the window.

Thanks for your response, It's working fine today.   I guess it was the issue with my laptop.
