### ISSUE TITLE
Crashes in Anki 23.10

### ISSUE THREAD

**Issue by ajdubovoy** [scottgigante/korean-support#39]
Seems like the Korean add on crashes in Anki 23.10. I get a popup when I open Anki that it failed to load this add on.

**Comment by scottgigante** [comment]
Hi @ajdubovoy , thanks for the flag. Unfortunately I don't have the time to update this package at the moment, though I will happily accept a pull request.

**Comment by threkk** [comment]
I have managed to get a working version of the add-on on my machine. It nails down to updating the references of `PyQT5` to `PyQT6`, and updating the `gTTS` submodule, so it removes the dependency on `six`. I was working on a patch, but the submodule set up got on the way.

**Comment by scottgigante** [comment]
@threkk could you open a PR with the changes you made? I'm happy to do the rest.

**Comment by threkk** [comment]
That would be an overkill, as I only replaced `PyQt5` with `PyQt6`  [here](https://github.com/scottgigante/korean-support/blob/master/korean/about.py#L1).

Regarding `gTTS`, for my local installation, as I cannot easily update the package, added `six` as a package. This should not be needed if you can update the dependency because upstream `six` is not a dependency any more.

The gist of the problem seems to be that with the release of the latest versions of Anki, they replaced QT5 with QT6, and removed the support for Python 2, which also removed the `six` library. The current version upstream of `gTTS` does not use `six`, but the one pinned in the submodule does.

**Comment by scottgigante** [comment]
I tried the solution you suggested, but unfortunately in the intervening time both formatting and CI have become outdated and will need to be fixed. I don't have any bandwidth to work on this -- I don't use Anki anymore nor do I study Korean, so I'm only maintaining this out of goodwill. I'm happy to review and merge PRs. You would need to:

* open a PR from gTTS head to my fork of gTTS as in https://github.com/scottgigante/gTTS/pull/1 (conflicts need resolving)
* open a PR to this repo updating PyQT6, fixing CI / linting errors, and updating the commit of the subrepository to the new merged head of my fork of gTTS

I will happy review, merge and release if someone is willing to do this.

**Comment by Kiina** [comment]
I have created a merge request for gTTS. Did a test with my fork of korean-support with the CI errors and PyQT fixed and the TTS is generated. Can update the submodule in the fork when it's merged and do a pull request for korean-support.

**Comment by scottgigante** [comment]
Merged, thank you!

**Comment by scottgigante** [comment]
Thanks to @Kiina we now have a new version released on Ankiweb. Please let me know if the issue persists.
